### ISSUE TITLE
Vectorize compton subtraction loop / reimplement it

### ISSUE THREAD

**Issue by jorgenem** [oslocyclotronlab/ompy#1]
The bottleneck to unfolding is the compton subtraction. It is highly parallelizable, and the easiest route to make it more efficient is probably to vectorize over the Ex axis. Hopefully it is not too difficult, it just requires some care with the axes.

**Comment by fzeiser** [comment]
At f158a90a48a7f092faafdf7bf0cf2414d67eefa1, the Compton subtraction is missing.

**Comment by fzeiser** [comment]
Will be fixed in #38
