### ISSUE TITLE
Matrix class as subclass of numpy ndarray? 

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/ompy#10]
Wouldn't it be  good to have the matrix class be a subclass of `ndarray`? Then you can run all `numpy` functions eg. on the `om.firstgen` object itself, instead of having to call `om.firstgen.matrix` every time.

For implementation:
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.subclassing.html#slightly-more-realistic-example-attribute-added-to-existing-array

Note that we should change the name from `matrix`to something else then, in order to not confuse it with `numpy.matrix`. Eg. the class could be called `OsloMatrix` or maybe rather `OsloArray`

**Comment by fzeiser** [comment]
Cannot have been closed in 6c93485, can it? Nothing addressed in this regard. @jorgenem: Which #10 did you refer to?

**Comment by jorgenem** [comment]
I didn't mean to close anything. This is one of the many times when I feel like Github controls me more than the other way around... :-)

**Comment by fzeiser** [comment]
My bad! Actually it was me who wrote a wrong commit message for some reason.

**Comment by Caronthir** [comment]
Subclassing ndarray is unrealistic at this stage. Using normal dunder methods is planed.
