### ISSUE TITLE
Problem in ensemble.py? 

### ISSUE THREAD

**Issue by cecgresonant** [oslocyclotronlab/ompy#107]
I tested the Ensemble class for my 186W matrix, and it worked nicely for 10 perturbed members as in the documentation example. However, when I tried 100 perturbed members I got the following error at the end, after a seemingly successful generation of 100 perturbed matrices:

``` pytb
[...]
2020-01-18 11:40:11,703 - ompy.ensemble - INFO - Generating 97
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 96/100 [02:30<00:05,  1.47s/it]2020-01-18 11:40:12,850 - ompy.ensemble - INFO - Generating 98
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 97/100 [02:32<00:05,  1.72s/it]2020-01-18 11:40:15,166 - ompy.ensemble - INFO - Generating 99
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:36<00:00,  1.56s/it]
Traceback (most recent call last):
  File "ompy_186W_script.py", line 115, in <module>
    ensemble.generate(100, regenerate=True)
  File "/Applications/ompy/ompy/ensemble.py", line 230, in generate
    raw_ensemble = ensembles[:, 0, :, :]
IndexError: too many indices for array
```

Is this a bug in ensemble.py? I attach the python script and my input raw matrix as .txt files. 
[alfna_recal_cutd_comp.txt](https://github.com/oslocyclotronlab/ompy/files/4085742/alfna_recal_cutd_comp.txt)

[ompy_186W_script.txt](https://github.com/oslocyclotronlab/ompy/files/4085748/ompy_186W_script.txt)

**Comment by fzeiser** [comment]
I'll look at it tonight

**Comment by fzeiser** [comment]
I'll have to look at the exact problem later. For now, if you want to work with the matrices, introduce a "reasonable" cut, eg.

``` py
raw.cut('Ex', 0, 10000)
raw.cut('Eg', 0, 10000)
```

This will speedup the calculations, too.

**Comment by fzeiser** [comment]
When I run it with 10 without the modificaiton, it doesn't work either.

**Comment by fzeiser** [comment]
Well, as I said, I'll come up with a fix for it later :smile:.

**Comment by fzeiser** [comment]
I think it's negative `Ex` that it doesn't like, but I'll come back with a more elaborate solution later. So the important part is the lower cuts.
