### ISSUE TITLE
Refactor save/load 1d

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/ompy#115]
Working on percistency for some classes, and looking through this realized that the `Vectors` are saved as a one column vector, appending values and energies. I think this is rather ugly, much easier if we have two columns, energy and values.

https://github.com/oslocyclotronlab/ompy/blob/77e30bfcc77a51cd2428e7758f03e6373bc1c86e/ompy/filehandling.py#L266-L270

@vetlewi : Do you by any chance use save/load already? I don't want to break your code ;P, but otherwise I'd like to change it. It's not really important, but still :smile:

**Comment by vetlewi** [comment]
I don't think so, no.
