### ISSUE TITLE
Bug in ensemble unfolding of spectra (dummy matrix)?

### ISSUE THREAD

**Issue by dortheg** [oslocyclotronlab/ompy#130]
Ompy version: 1.0.1.dev0+84c50c6

I run the unfolding using only one excitation energy bin. When trying to extract the standard deviations using the Ensemble class, my matrix is split in two excitation energy bins, each and each bin has different values for the standard deviations.

![std](https://user-images.githubusercontent.com/21241136/84630141-ca221400-aeeb-11ea-9137-6f2d19cda6e0.png)
![unfolded](https://user-images.githubusercontent.com/21241136/84630144-cabaaa80-aeeb-11ea-91fa-d6b45c652989.png)

**Comment by fzeiser** [comment]
Please provide a minimal working example such that this bug can be reproduced

**Comment by fzeiser** [comment]
I'll create one for you here as I was already working on it.

**Comment by fzeiser** [comment]
Here is an almost minimal working example with run with version `1.0.1.dev0+84c50c6`.

I don't think this is a bug, it's a "feature". When you unfold the first time, you unfold the raw matrix, `unfolded = unfolder(raw_positive)`. No background subtraction occurred here, thus both (dummy) Ex bins have the same spectrum.
In the ensemble unfolding, you now request to:
- generate the `raw_wo_bg` spectrum from `raw` (including background) and `bg` spectra; redraw bins according to poisson distribution for each ensemble member.
- unfold each ensemble member.

Because of the redraw, `raw_wo_bg` will look differently for each ensemble member -- and for each excitation energy. The algorithm assumes that the Ex bins are uncorrelated - which is usually very reasonable - but infact, here, they are 100% correlated.

You can see the behavior even before unfolding if you look at the generated raw matric(es):
``` py
ensemble.get_raw(0).plot()
ensemble.get_raw(1).plot()
[...]
```

``` py
import ompy as om
import matplotlib.pyplot as plt
import numpy as np
import logging

om.__full_version__

# create a dummy matrix somewhat like issue #130
raw = om.example_raw('Dy164')
raw.cut(axis="Ex", Emin=5000, Emax=5100)


raw = om.Matrix(values=[raw.values[0, :], raw.values[0, :]],
                Ex=[1, 2], Eg=raw.Eg)
raw.rebin(axis="Eg", factor=10)
raw.plot()

bg = raw.copy()
bg.values *= 0.1
bg.plot()
plt.show()

logger = om.introspection.get_logger('response', 'INFO')
# folderpath = "../FYS4515/ompy/oscar_response/oscar2017_scale1.15"
folderpath = "../../misc/ompy/OCL_response_functions/oscar2017_scale1.15"

# Magne recommends 1/10 of the actual resolution for unfolding purposes
response = om.Response(folderpath)
R_ompy_unf, R_tab_unf = response.interpolate(
    raw.Eg, fwhm_abs=34. / 10.0, return_table=True)

raw_positive = raw.copy()
raw_positive.fill_and_remove_negative(window_size=2)

# With compton subtraction and all tweaks
unfolder = om.Unfolder(response=R_ompy_unf)
unfolder.use_compton_subtraction = True  # default
unfolder.response_tab = R_tab_unf

# Magne suggests some "tweaks" for a better unfolding performance. Default
# is 1 for all.
# unfolder.FWHM_tweak_multiplier = {"fe": 1., "se": 1.1, "de": 1.3, "511": 0.9}
unfolded = unfolder(raw_positive)
unfolded.plot()

# dummy firstgen to make the ensemble class work
firstgen = om.FirstGeneration()
primary = firstgen(unfolded)
# primary.plot()

logger1 = om.introspection.get_logger("ensemble", "INFO")

ensemble = om.Ensemble(raw=raw, bg=bg)
ensemble.unfolder = unfolder
ensemble.first_generation_method = firstgen
ensemble.generate(10, regenerate=True)

ensemble.get_unfolded(0).plot()
ensemble.get_unfolded(1).plot()
ensemble.std_unfolded.plot()
plt.show()
```

**Comment by fzeiser** [comment]
If (/once) the issue is solved, please close it. 
Otherwise, if you have further questions, please feel free to post here.

**Comment by dortheg** [comment]
There's a couple of things I don't understand:

1) I first tried using the Ensemble class only for the `raw_positive` matrix:

`ensemble = om.Ensemble(raw_positive)`

 and I still get two excitation energy bins in `std_unfolded`. From your explanation, it seems like this should occur because of the background subtraction `_all - bg`, so why does it also happen for the already bg-subtracted matrix?

2) Why is my single bin split in two bins, and not three, four, ten...?

3) If it, in fact, should be two different bins in `std_unfolded` for one excitation energy bin, then I must take the mean of these two (or: sqrt(sigma_1^2 + sigma_2^2)). It is fine doing this for one bin, but if I have 600 bins, it'll be troublesome, especially since the bin number in the unfolded matrix does not match the bin number in the standard deviation matrix. 

Also, I disagree with my matrix being "dummy" - it is 252Cf fission-gammas data, it's just forced into matrix format as Ompy's unfolder procedure doesn't take a vector.

**Comment by fzeiser** [comment]
What do you mean by a single bin being split? Following line creates a matrix with two `Ex` bins from a vector, which doesn't have a `Ex` bin:
``` py
raw = om.Matrix(values=[raw.values[0, :], raw.values[0, :]],
                Ex=[1, 2], Eg=raw.Eg)
```

> Also, I disagree with my matrix being "dummy" - it is 252Cf fission-gammas data, it's just forced into matrix format as Ompy's unfolder procedure doesn't take a vector.

The matrix class is designed for a particle-gamma coincidence matrix, hence the `Ex` label (and `Eg`). As we create the matrix here just as a workaround for the unfolder class, I call it a *dummy* matrix -- maybe *mock* matrix would describe it better.

**Comment by dortheg** [comment]
Oh, I thought `Ex = [1,2]` was "one excitation energy bin with a 1 MeV width".

**Comment by fzeiser** [comment]
No, the axis are given with their mid-bin values:
```
            Eg: The gamma ray energies using midbinning.
            Ex: The excitation energies using midbinning.
```
and analogously for `om.Vector`.

**Comment by dortheg** [comment]
Aha, thank you! And as the number of bins in a matrix must be greater than 1, and thus I'm stuck with two excitation energy bins.

So it's a "feature" until `unfolder` takes vectors, not only matrices

**Comment by dortheg** [comment]
- [ ]

**Comment by fzeiser** [comment]
> And as the number of bins in a matrix must be greater than 1, and thus I'm stuck with two excitation energy bins.

More precisely, some (but not all) functions acting on `om.Matrix` will require that the it has more than 1 `Ex` bin.
