### ISSUE TITLE
Add option to rebin matrix in both axis simultaneously

### ISSUE THREAD

**Issue by vetlewi** [oslocyclotronlab/ompy#132]
I use the `matrix.rebin()` method quite frequently and quite often I want to rebin both axis at the same time with the same binning. The way the method is now I will have to first rebin one axis and then the other:
```python
raw = om.Matrix(path="raw.m")
new_bins = np.linspace(0, 10000, 501)
raw.rebin('Ex', mids=new_bins)
raw.rebin('Eg', mids=new_bins)
```
This could be simplified if one also could call
```python
new_bins = np.linspace(0, 10000, 501)
raw.rebin('both', mids=new_bins)
```

I guess this could be implemented by adding a third option here
https://github.com/oslocyclotronlab/ompy/blob/c64346092e27ce8df7af1ca9c175b65fadea2e31/ompy/matrix.py#L677-L679

and then something like
```python
if axis == 3:
    return self.rebin(0, mids=mids, factor=factor, inplace=inplace).rebin(1, mids=mids, factor=factor, inplace=inplace)
```

**Comment by fzeiser** [comment]
Good suggestion, do you want to implement it?

`to_plot_axis` already will spit out "2" for "both":
https://github.com/oslocyclotronlab/ompy/blob/e12d8b1dfe756f8b1c032e83bfa8337ed08eca3c/ompy/abstractarray.py#L160-L165

Keep in mind that you cannot chain the way you suggestion when `inplace=False`.
If you should have a look at the function, you're welcome to refactor it. It doesn't look so nice the way it is now, but I never bothered to clean up.

**Comment by vetlewi** [comment]
> Good suggestion, do you want to implement it?
Can do :)

> 
> `to_plot_axis` already will spit out "2" for "both":
> 
> https://github.com/oslocyclotronlab/ompy/blob/e12d8b1dfe756f8b1c032e83bfa8337ed08eca3c/ompy/abstractarray.py#L160-L165
> 
> Keep in mind that you cannot chain the way you suggestion when `inplace=True`.
Yes, I see that it has to be handled separately for the two cases.

> If you should have a look at the function, you're welcome to refactor it. It doesn't look so nice the way it is now, but I never bothered to clean up.
Maybe, I'll let you know if I do a refactor
