### ISSUE TITLE
Problems reading discrete states from file

### ISSUE THREAD

**Issue by vetlewi** [oslocyclotronlab/ompy#133]
When initialising the `NormalizerNLD` class I get the following assertion error:
```
~/Git_Repositories/ompy/ompy/filehandling.py in load_discrete(path, energy, resolution)
    343     energies /= 1e3  # convert to MeV
    344     if len(energies) > 1:
--> 345         assert energies.mean() < 5, "Probably energies are not in keV"
    346 
    347     binsize = energy[1] - energy[0]

AssertionError: Probably energies are not in keV
```
I guess that the reason I get this error is because many of the states I have in the file is above 5 MeV.  The minimum mean energy should probably be larger, say 50 or even 500.

**Comment by fzeiser** [comment]
I'd go for 10 -- for the Oslo method you really shouldn't have a mean of the discrete's of more then 10 MeV. If you take 500, it might get tricky for the with heavy nuclei.

**Comment by fzeiser** [comment]
went for 20 after a second though
