### ISSUE TITLE
Vector class doesn't store the `std` attribute

### ISSUE THREAD

**Issue by vetlewi** [oslocyclotronlab/ompy#140]
When I save a `Vector` object to file I would expect that all the attributes would be saved such that all attributes would be the same after loading back from file.

**Comment by fzeiser** [comment]
Hei! That's indeed a bug. It can be changed for saving in numpy format and plain text, but not directly for mama. Therefore I propose to check if `std` is set. If if not, proceed as before. If it is, create an additional file with `[...]_std`; and the corresponding thing with the load function; it might be nice to set a `debug` message to the logger.

For numpy/plain text one could also just save the additional column; that would be easier.

**Comment by vetlewi** [comment]
I see that this is also missing for the `Matrix` class.

I'm currently trying to implement a fix.
How about giving the user a warning if trying to save in MaMa format while the `std` is set?

**Comment by vetlewi** [comment]
> For numpy/plain text one could also just save the additional column; that would be easier.

This will break backwards compatibility, is that OK?

**Comment by fzeiser** [comment]
I don't see how it breaks the compatibility; it's just that the attributes will not be loaded with the old versions, isn't it?

https://github.com/oslocyclotronlab/ompy/blob/be782f2cfc2ea89cbdfd23856ea554a3501adcef/ompy/filehandling.py#L280-L310

**Comment by fzeiser** [comment]
> How about giving the user a warning if trying to save in MaMa format while the `std` is set?

ok
