### ISSUE TITLE
Simultaneous Normalizer not running, unless the NLD and gsf has already been normalized.

### ISSUE THREAD

**Issue by tellefs** [oslocyclotronlab/ompy#150]
Running
`simnorm = om.NormalizerSimultan(normalizer_nld=nldnorm, normalizer_gsf=gsfnorm, regenerate=regenerator)`
`simnorm.normalize()`
yields an error in `alpha = normalizer_nld.res.pars["alpha"][0]` from `normalizer_gsf.py`.

The simultaneous normalization seems to work, if I first run the sequential normalizations `nldnorm.normalize()` and `gsfnorm.normalize()`.

**Comment by fzeiser** [comment]
Thanks for submitting this issue. could you post the whole error message?

**Comment by tellefs** [comment]
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-231e9530f8a6> in <module>
      7 # For propper calc. you may rather increase this to > 400.
      8 simnorm.multinest_kwargs["n_live_points"] = 1000
----> 9 simnorm.normalize()
     10 
     11 #plot normalization

~/ompy/ompy/normalizer_simultan.py in normalize(self, num, gsf, nld, normalizer_nld, normalizer_gsf)
    154 
    155         # Use DE to get an inital guess before optimizing
--> 156         args_nld, guess = self.initial_guess()
    157         # Optimize using multinest
    158         popt, samples = self.optimize(num, args_nld, guess)

~/ompy/ompy/normalizer_simultan.py in initial_guess(self)
    203         nld_model = lambda E: normalizer_nld.model(E, T=T, Eshift=Eshift)  # noqa
    204 
--> 205         normalizer_gsf.normalize(nld=nld, nld_model=nld_model)
    206         guess["B"] = normalizer_gsf.res.pars["B"][0]
    207 

~/ompy/ompy/normalizer_gsf.py in normalize(self, gsf, normalizer_nld, alpha, nld, nld_model, norm_pars, num)
    170         if alpha is None:
    171             self.LOG.debug("Setting alpha from from normalizer_nld")
--> 172             alpha = normalizer_nld.res.pars["alpha"][0]
    173         assert alpha is not None, \
    174             "Provide alpha or normalizer_nld with alpha"

TypeError: list indices must be integers or slices, not str`

**Comment by tellefs** [comment]
It also prints the initial DE results before the error: 
`2020-10-09 10:16:01,602 - ompy.normalizer_nld - INFO - DE results:
┌───────────────────┬───────────┬────────────────────┬─────────────────────┐
│ A                 │ α [MeV⁻¹] │ T [MeV]            │ Eshift [MeV]        │
╞═══════════════════╪═══════════╪════════════════════╪═════════════════════╡
│ 8.234508241328987 │ 0.1       │ 0.8678120926272002 │ -2.5446587875441526 │
└───────────────────┴───────────┴────────────────────┴─────────────────────┘`

**Comment by fzeiser** [comment]
From telef: 
> After the #150 issue was fixed, the SimNorm is now running, without running the sequential NLD and gSF normalizations first.
> 
> However, i get completely different normalizations if i run them berfore the SimNorm or not.
> 
> First plot, is the SimNorm, after running the sequentials.
> ![normalized_nld_gsf_postSeqNorm](https://user-images.githubusercontent.com/16207591/95592561-18ce5d80-0a49-11eb-9713-21e204b736d2.png)
> 
> Without changing the nomalization params., just removing the sequential normalizations, my SimNorm looks like this
> 
> ![normalized_nld_gsf_preSeqNorm](https://user-images.githubusercontent.com/16207591/95592697-4f0bdd00-0a49-11eb-9cd1-49ba2e21ac3f.png)

**Comment by fzeiser** [comment]
Can you print the DE results in both cases?
For case 1, please print DE of normalizer_nld and normalizer_simulatneous

**Comment by fzeiser** [comment]
I found parts of (?) them in your repo:
https://github.com/tellefs/OmPy_233U/blob/530693553988391b08d893ec26ad0d6474c93173/osloMethod_U233_aa.ipynb

**Case B)**
NLD normalizer
```
2020-10-09 16:09:59,054 - ompy.normalizer_nld - INFO - 

---------
Normalizing nld #0
2020-10-09 16:10:00,099 - ompy.normalizer_nld - INFO - DE results:
┌───────────────────┬───────────┬────────────────────┬─────────────────────┐
│ A                 │ α [MeV⁻¹] │ T [MeV]            │ Eshift [MeV]        │
╞═══════════════════╪═══════════╪════════════════════╪═════════════════════╡
│ 8.234508241328987 │ 0.1       │ 0.8678120926272002 │ -2.5446587875441526 │
└───────────────────┴───────────┴────────────────────┴─────────────────────┘
2020-10-09 16:10:00,101 - ompy.normalizer_nld - INFO - Starting multinest
  analysing data from multinest/nld_norm_0_.txt
2020-10-09 16:10:16,380 - ompy.normalizer_nld - INFO - Multinest results:
┌───────────┬─────────────┬─────────────┬──────────────┐
│ A         │ α [MeV⁻¹]   │ T [MeV]     │ Eshift [MeV] │
╞═══════════╪═════════════╪═════════════╪══════════════╡
│ 8.5 ± 1.8 │ 0.10 ± 0.48 │ 0.81 ± 0.34 │ -2.2 ± 1.8   │
└───────────┴─────────────┴─────────────┴──────────────┘
2020-10-09 16:10:16,381 - ompy.normalizer_nld - INFO - Saving to saved_run/normalizers/NormalizerNLD.pkl
```
Simnorm : 
```
2020-10-09 16:10:17,435 - ompy.normalizer_nld - INFO - DE results:
┌──────────────────┬───────────┬────────────────────┬────────────────────┐
│ A                │ α [MeV⁻¹] │ T [MeV]            │ Eshift [MeV]       │
╞══════════════════╪═══════════╪════════════════════╪════════════════════╡
│ 8.23435295291474 │ 0.1       │ 0.8678205079676372 │ -2.544735000977775 │
└──────────────────┴───────────┴────────────────────┴────────────────────┘
2020-10-09 16:10:17,494 - ompy.normalizer_gsf - INFO - Normalizing #0
2020-10-09 16:10:17,500 - ompy.normalizer_simultan - INFO - DE results/initial guess:
┌──────────────────┬───────────┬────────────────────┬────────────────────┬───────────────────┐
│ A                │ α [MeV⁻¹] │ T [MeV]            │ Eshift [MeV]       │ B                 │
╞══════════════════╪═══════════╪════════════════════╪════════════════════╪═══════════════════╡
│ 8.23435295291474 │ 0.1       │ 0.8678205079676372 │ -2.544735000977775 │ 41858.99458486805 │
└──────────────────┴───────────┴────────────────────┴────────────────────┴───────────────────┘
2020-10-09 16:10:17,501 - ompy.normalizer_simultan - INFO - Starting multinest: 
  analysing data from multinest/sim_norm_0_.txt
2020-10-09 16:12:10,188 - ompy.normalizer_simultan - INFO - Multinest results:
┌───────────┬───────────────┬─────────────┬──────────────┬─────────┐
│ A         │ α [MeV⁻¹]     │ T [MeV]     │ Eshift [MeV] │ B       │
╞═══════════╪═══════════════╪═════════════╪══════════════╪═════════╡
│ 8.8 ± 1.6 │ 0.028 ± 0.032 │ 0.87 ± 0.14 │ -2.49 ± 0.89 │ 26 ± 14 │
└───────────┴───────────────┴─────────────┴──────────────┴─────────┘
2020-10-09 16:12:10,193 - ompy.normalizer_simultan - INFO - Saving to saved_run/normalizers/NormalizerSimultan.pkl

```

I think the Problem could be the boundary conditions for DE, such that it doesn't find a good solution.

**Comment by fzeiser** [comment]
I think I cannot reproduce your problem. 
I'll attach my slightly modified example: 
[osloMethod_U233_aa.ipynb.zip](https://github.com/oslocyclotronlab/ompy/files/5356007/osloMethod_U233_aa.ipynb.zip)


Pseudocode:
```
nldnorm, gsfnorm = init_norms()
case1 = simulateous_normalizer(nldnorm, gsfnorm)

nldnorm, gsfnorm = init_norms()
nldnorm.normalize()
gsfnorm.normalize()
case2 = simulateous_normalizer(nldnorm, gsfnorm)
```

Then case1 == case 2 and the normalization seems to look just fine.
[I think i switched case 1 and 2 regarding what you wrote, but otherwise that should be it, right?]
![image](https://user-images.githubusercontent.com/15156776/95603762-03603000-0a57-11eb-85e8-176f82942bcb.png)
But there is one thing that is interesting. It seems like DE is not propperly seeded as I get slightly(!) different results for both cases.

**Comment by fzeiser** [comment]
Ah, I see: You commented out the seeding of the notebook. Anyhow, it might be good to seed DE in general, just as we do for Multinest (...)

**Comment by tellefs** [comment]
Left the seed in. Normalizations looks better now, thanks for helping!
