### ISSUE TITLE
Strange Simultaneous Normalization

### ISSUE THREAD

**Issue by tellefs** [oslocyclotronlab/ompy#152]
After the #150 issue was fixed, the SimNorm is now running, without running the sequential NLD and gSF normalizations first. 

However, i get completely different normalizations if i run them berfore the SimNorm or not.

First plot, is the SimNorm, after running the sequentials.
![normalized_nld_gsf_postSeqNorm](https://user-images.githubusercontent.com/16207591/95592561-18ce5d80-0a49-11eb-9713-21e204b736d2.png)

Without changing the nomalization params., just removing the sequential normalizations, my SimNorm looks like this 

![normalized_nld_gsf_preSeqNorm](https://user-images.githubusercontent.com/16207591/95592697-4f0bdd00-0a49-11eb-9cd1-49ba2e21ac3f.png)

**Comment by fzeiser** [comment]
discussing in the old thread instead...
