### ISSUE TITLE
Install error: ModuleNotFoundError: No module named 'pybind11.setup_helpers'

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/ompy#159]
When tying to installing ompy at ba02e83 I get following error:
```pytb
❯ pip install -e .
Obtaining file:///home/fabiobz/Desktop/Masterthesis/misc/ompy
    ERROR: Command errored out with exit status 1:
     command: /home/fabiobz/miniconda3/envs/myenv/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/fabiobz/Desktop/Masterthesis/misc/ompy/setup.py'"'"'; __file__='"'"'/home/fabiobz/Desktop/Masterthesis/misc/ompy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/fabiobz/Desktop/Masterthesis/misc/ompy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/fabiobz/Desktop/Masterthesis/misc/ompy/setup.py", line 10, in <module>
        from pybind11.setup_helpers import Pybind11Extension
    ModuleNotFoundError: No module named 'pybind11.setup_helpers'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Will check this, but I assume it's about the pybind version.

**Comment by vetlewi** [comment]
Do you have PyBind11 installed? (pip install pybind11)

**Comment by fzeiser** [comment]
Yes, but as I assumed it was the pybind11 version. `setup_helpers` is part of the package since 2.6.0,  see https://github.com/pybind/pybind11/blob/master/docs/changelog.rst

Will fix the requirements file.

**Comment by fzeiser** [comment]
So I'll fix it in the requirements, but the error message can still come up, because pip reads the setup file before it knows about the requirements. Anyhow, it should be easy enough for people to figure out -- at least with this thread here.

**Comment by vetlewi** [comment]
> So I'll fix it in the requirements, but the error message can still come up, because pip reads the setup file before it knows about the requirements. Anyhow, it should be easy enough for people to figure out -- at least with this thread here.
> 
> Alternatively, one could add a couple of `try import ...` and version checks, but that seems a little too much.

Or maybe add a note on prerequisites in the readme? `pip install -e .` or `pip install .` will fail if either `numpy`, `cython` or `pybind11` isn't installed.

Something like:
### Prerequisites
Before installing the OMpy package the following dependencies needs to be installed **BEFORE** OMpy:

- `Numpy`: `pip install numpy`
- `Cython`: `pip install cython`
- `pybind11`: `pip install pybind11`

### Common errors

> I get error `ModuleNotFoundError: No module named 'pybind11.setup_helpers'`
-  You're probably missing `pybind11` or have an outdated version (<2.6). Install or update `pybind11`: `pip install --upgrade pybind11`

**Comment by vetlewi** [comment]
> So I'll fix it in the requirements, but the error message can still come up, because pip reads the setup file before it knows about the requirements. Anyhow, it should be easy enough for people to figure out -- at least with this thread here.
> 
> Alternatively, one could add a couple of `try import ...` and version checks, but that seems a little too much.

Actually, this can be fixed by adding a `pyproject.toml` file to the project root dir. See PR #160.
