### ISSUE TITLE
Warning for unconstrained elements in `Extractor`

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/ompy#173]
As @vetlewi suggested in #170, it's probably smart to add a warning when the results of `Extractor` contain elements that were not constrained (and therefore set to `np.nan`).

I could imagine two alternatives:
- warn if (any) nld / gsf contains `nan`s
- warn if (any) nld / gsf contains `nan`s for `E>0`.

I would suggest the first version, as the nld minimum energy is - at least currently - determined from 
https://github.com/oslocyclotronlab/ompy/blob/05a3a503866acdfa36931fbb01c9d8eb337495fc/ompy/extractor.py#L251-L254

which can easily end up e.g. at -2 MeV. Whether counts in this energy range (*if* existent) will be considered for the decomposition, depends on the choice of the resolution. This being said, the suggestion in the `gettingstarted` notebook is to set `extend_fit_by_resolution = False # (= default)`. 

So I suggest a check along the line of this for both nld and gsf:
``` py
for i, vec in enumerate(self.nld):
    if np.isnan(vec.values).any():
        contains_nan = True
        LOG.warning(f"nld #{i} contains nan's.\n"
                    "Consider removing them e.g. with:\n"
                    "# for nld in extractor.nld:\n"
                    "#     nld.cut_nan()\n")
```

**Comment by vetlewi** [comment]
> As @vetlewi suggested in #170, it's probably smart to add a warning when the results of `Extractor` contain elements that were not constrained (and therefore set to `np.nan`).
> 
> I could imagine two alternatives:
> 
> * warn if (any) nld / gsf contains `nan`s
> * warn if (any) nld / gsf contains `nan`s for `E>0`.
> 
> I would suggest the first version, as the nld minimum energy is - at least currently - determined from
> 
> https://github.com/oslocyclotronlab/ompy/blob/05a3a503866acdfa36931fbb01c9d8eb337495fc/ompy/extractor.py#L251-L254
> 
> which can easily end up e.g. at -2 MeV. Whether counts in this energy range (_if_ existent) will be considered for the decomposition, depends on the choice of the resolution. This being said, the suggestion in the `gettingstarted` notebook is to set `extend_fit_by_resolution = False # (= default)`.
> 
> So I suggest a check along the line of this for both nld and gsf:
> 
> ```python
> for i, vec in enumerate(self.nld):
>     if np.isnan(vec.values).any():
>         contains_nan = True
>         LOG.warning(f"nld #{i} contains nan's.\n"
>                     "Consider removing them e.g. with:\n"
>                     "# for nld in extractor.nld:\n"
>                     "#     nld.cut_nan()\n")
> ```

It should also make it clear to the user that if there is `np.nan` at energies above 0 MeV (ie. issue #170) there might be problems down the line when normalizing the gsf.

The fact that there is `np.nan` (at least at Ex > 0 MeV) means that the user might have chosen the trapezoid cut poorly and could be mentioned (might be information overflow though).

**Comment by fzeiser** [comment]
I guess there are two issues then:
- I assume that you will anyhow have a problem if you have `np.nan`'s in the vectors and you should cut them away
- If you after cutting them away run into the issue that the nld doesn't extend to 0, you will have problems in the Gg normalization

So maybe to (separate) warning messages are appropriate?

**Comment by fzeiser** [comment]
With the currently proposed solution, you would probably cut all `np.nan`s away. If e.g. nld.E[0] = 2 MeV (and the bin-width = 100 keV), then you would get an error in NormalizerGSF (following #170). So I think the current solution maybe already holds?

Note: 
Depending on ones solution, one may want to normalize the extended / extrapolated nld already in `NormalizerNLD` and not not only after that. But that depends really.
