### ISSUE TITLE
Saving multinest results to desired path

### ISSUE THREAD

**Issue by tellefs** [oslocyclotronlab/ompy#176]
To my knowledge, the multinest results are now saved in the "multinest" directory, in the same directory as the normalization is run in. It would be preferable to beeing able to chose a path to save the results, like one can do with e.g. the Extractor and Normalizers.

**Comment by fzeiser** [comment]
You can change the default path to save the results via the `multinest_path` attribute:

https://github.com/oslocyclotronlab/ompy/blob/70c3d662dd1e922b0d00e35437d8122285678089/ompy/normalizer_simultan.py#L25-L33
