### ISSUE TITLE
Ability to use old NaI response function

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/ompy#22]
Some users may want to use ompy on old data sets taken with the NaI array Cactus. For support of this, one would have to read be able to read the NaI reponse function (files).

Implementation suggestion:
Create a `resp.dat` file with the same information content as now hardcoded in mama. May be quite easy to get from the excel sheet Magne used.

**Comment by vetlewi** [comment]
I'm sort of addressing this issue in PR #62. I'm wondering if we should make a response function repository, not only for OSCAR? (Just so I have somewhere to put the RF once I've compiled them together :p)

**Comment by fzeiser** [comment]
Let's discuss further in PR #62.

**Comment by fzeiser** [comment]
Implemented in #65
