### ISSUE TITLE
Implement response function manipulation

### ISSUE THREAD

**Issue by jorgenem** [oslocyclotronlab/ompy#3]
It should be possible to change the calibration of the response functions inside pyma, instead of having to supply a response with the correct bin width etc. from MAMA. It may be that the easiest route is to compile the response routine from MAMA with f2py.

**Comment by jorgenem** [comment]
Fixed in 9ca2e3ecb5632388b02bb495c81a951390ff8a8c

**Comment by Caronthir** [comment]
The function `interpolate_response` does not give expected results in the case of Dy163.

![Screenshot_2019-09-04_16-11-03](https://user-images.githubusercontent.com/11619231/64262704-c7db6400-cf2e-11e9-873e-bb074115e105.png)

**Comment by fzeiser** [comment]
Found the "mistake". We probably just had a /very/ wrong fwhm for the smoothing. In the linear scale shown here we then get some smoothing of counts up to quite high energies.

However, when going through this, I found a bug for the response at ~511 keV incident energy. I'll upload the corrections asap. (tomorrow?)

**Comment by fzeiser** [comment]
See commit message. I improved the interpolation for low energies. (Esp. below the 1. simulated spectrum and or bacscatter peak).

Status can be seen in `notebooks/code_testing/resp` and the notebook `test_response_function_interpolation.ipynb`.

A visual comparison (pasting in the files)
![response_compare_1](https://user-images.githubusercontent.com/15156776/64403753-0a5d8780-d07a-11e9-9f28-525e24a4c029.png)

![response_compare_2](https://user-images.githubusercontent.com/15156776/64403765-147f8600-d07a-11e9-9747-af922c06e556.png)

But the comparison to geant4 (see notebook for comments)
![resp_600](https://user-images.githubusercontent.com/15156776/64403782-24976580-d07a-11e9-9556-6cf713fad346.png)

![resp_3000](https://user-images.githubusercontent.com/15156776/64403786-27925600-d07a-11e9-8432-4213a7e580fb.png)

**Comment by fzeiser** [comment]
@Caronthir: For now, I'd use FWHM = 2.27 for Oscar!

**Comment by fzeiser** [comment]
@Caronthir: Implemented the FWHM read-out differently in #38. How it should be absolute fwhm 1.33 MeV, which is around 30 for oscar. Be aware of changes when you merge it in.

Resp interpolation is now similar to the above. But have a look at the notebook/pictures in the code test folder.
