### ISSUE TITLE
"Build" broken in current rhosig branch

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/ompy#31]
In the current rhosig branch I'm able to build ompy and install it, but when importing I get following error:

``` sh
>>> import ompy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fabiobz/Desktop/Masterthesis/misc/ompy_pub/ompy/__init__.py", line 6, in <module>
    from .fit_rho_T import *
  File "/home/fabiobz/Desktop/Masterthesis/misc/ompy_pub/ompy/fit_rho_T.py", line 37, in <module>
    from .matrix import Matrix
  File "/home/fabiobz/Desktop/Masterthesis/misc/ompy_pub/ompy/matrix.py", line 47, in <module>
    from .decomposition import index
ModuleNotFoundError: No module named 'ompy.decomposition'
```
@Caronthir Could you check whether you forgot to upload some files?

**Comment by fzeiser** [comment]
So it was again the directory of the files that are build from cython. I can fix it manually by
mv *.so ompy/

It can be solved by:
https://stackoverflow.com/questions/31043774/customize-location-of-so-file-generated-by-cython

**Comment by Caronthir** [comment]
This highlights an issue not earlier considered, namely that the build process has not been tested on different platforms. This should be fixed before the code is released.

**Comment by fzeiser** [comment]
Not relevant any longer. + Travis tests for different platform performed since #57
