### ISSUE TITLE
Add option to use rhosigchi estimate of first generation variance matrix

### ISSUE THREAD

**Issue by jorgenem** [oslocyclotronlab/ompy#4]
Rhosigchi presently estimates the first generation variance matrix using some analytical expressions. Pyma is built to estimate it using monte carlo error propagation. It should be possible to run pyma with the old estimate, to compare and also to get a fast estimate for the rho and T fit without having to run error propagation.

**Comment by fzeiser** [comment]
Apart from some manual tweaks  for systematic errors the old estimate was to generate the std. dev of the 1gen matrix from sqrt(N). One can easily perform this. I don't think that the systematic errors were so well checked, so I don't really want to implement them. If one only wants to compare the differences in the algorithms, one can import/export just before the decomposition or just after from/to rhosigchi.
