### ISSUE TITLE
PyMultiNest broken on macOS

### ISSUE THREAD

**Issue by vetlewi** [oslocyclotronlab/ompy#49]
The package PyMultiNest is unfortunately unable to locate the MultiNest libraries properly on macOS. I've forked the repo and added a fix here: https://github.com/vetlewi/PyMultiNest. I've implemented the fix in commit https://github.com/vetlewi/PyMultiNest/commit/8e87a43f594c1cffbc8921cdc4d3178029109992.

I'm also thinking of updating the package with automatic building of the Fortran library at the same time with pip. Let me know if we should push for such a fix.

**Comment by fzeiser** [comment]
I installed it successfully on Magne and Ann-Cecilies machines before, so we can check what the problem is.

**Comment by vetlewi** [comment]
The MultiNest library is loaded in the following lines:
https://github.com/JohannesBuchner/PyMultiNest/blob/20de0471003c08c68893aa17e33f97f4826e3006/pymultinest/run.py#L5-L21
Here the path given will be relative to the position where the library is ran from since `cdll.LoadLibrary` does not search for the library (at least for macOS). I fixed this by actively searching for the library binary in https://github.com/vetlewi/PyMultiNest/blob/8e87a43f594c1cffbc8921cdc4d3178029109992/pymultinest/run.py#L6-L21

**Comment by fzeiser** [comment]
Can you send a pull request to Johannes and close the issue when the pull request is merged in?

**Comment by vetlewi** [comment]
This has been fixed in mulitnest and the issue should be closed.
