### ISSUE TITLE
travis fails to find .travis.yml

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/ompy#56]
travis fails to build the lastest commits, with an error of the type `
Not found: oslocyclotronlab/ompy/.travis.yml@e7dd451c60b8d0e9 `

You can find it under More options > Requests

@Caronthir: Can you have a look at this?
(after finishing the gsf normalization).

We should also fix that travis automatically runs the tests and the getting started notebook.

**Comment by vetlewi** [comment]
I have travis working in my fork

**Comment by fzeiser** [comment]
Yep, I can't quite see why it should fail. I guess you didn't do any changes to get it working, but it just did so, right?

**Comment by vetlewi** [comment]
I've been changing the .travis.yml file though... To add macOS. See here: https://github.com/vetlewi/ompy/tree/TravisCI

**Comment by fzeiser** [comment]
Nice, we've anyhow thought of doing this ;P. But still, that's not the issue that comes up for me. I think Erlend set up travis for this repo, so maybe he can get some more information of the error.

**Comment by vetlewi** [comment]
The PR is building (and failing due to data/discrete_levels.txt is missing)

**Comment by fzeiser** [comment]
Let's continue the conversation on the PR #57 in it's own thread. However, this doesn't solve the issue here. 
`Not found: oslocyclotronlab/ompy/.travis.yml@e7dd451c60b8d0e9`

**Comment by fzeiser** [comment]
I think I see what the issue is now :/. The file ending might have been misspelled. Don't get when we moved the file, but here's the issue:
`travis.yaml`  vs `.travis.yml`
