### ISSUE TITLE
Trapezoid cut failure

### ISSUE THREAD

**Issue by vetlewi** [oslocyclotronlab/ompy#68]
I've been trying to run the extractor on an ensemble and for some reason the trapezoid cut won't cut correctly, leaving the shape of the first generation different from the std.

I cannot really understand why, since the cut works correctly the first iteration, but fails on the second. After digging a little, it seems to be related to the `Eg_max` found will give a different result.
I think the `trapezoid` cut method could be made more stable!

**Comment by fzeiser** [comment]
Sorry, I was aware of this already. Will be fixed when merging in 5409e4c61feb56c633bfeb38b70212e914afef01.

**Comment by vetlewi** [comment]
👏 👏 👏

**Comment by fzeiser** [comment]
There are several other issues that will be fixed in the same brach. Sorry for not updating the issues list, but I set a priority in writing the fixes instead of updating here. Anyhow, it should be merged in in a not too distant future. I hope :)

**Comment by vetlewi** [comment]
No worries! I guess this will be closed once it is merged!

**Comment by fzeiser** [comment]
After some rebasing it ended up beeing 4f84776d4143fc3cded8bd6447de0eda07e7b03e. Merged in master now.
