### ISSUE TITLE
Binning for fg fit and the detector resolution

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/ompy#79]
Currently, we implement fir the fg-matrix within some user-defined cuts, and with the constraint `Ex = Eg + dE`, where `dE` is the detector resolution calculated from the square-sum of the particle and gamma-detector resolution. This follows the implementation in `rhosigchi`. I think that this leads to confusing/erroneous results (if the binning is chosen narrower than the resolution) :
- We may receive nlds at negative Ex
- For the hightest Ex bins, following situation may occur:
<img width="799" alt="PNG image" src="https://user-images.githubusercontent.com/15156776/69040202-b7933b00-09ed-11ea-8a3f-d7d59e3c03fd.png">

- It is not clear why you should go out 1sigma, 2 sigma, ..., but due to the point mentioned above, this will effect the results

Instead, I propose to choose the binning as the fwhm of the resolution. As the the resolution increases for higher gamma-ray energies, there are two options:
- take the resolution of the "worst" point, i.E. at maximum gamma-ray energy (+ particle resolution)
- could we chose a non-linear binning here, too? I'm having some troubles to think of how we could still guarantee that we git the same nld at different cuts along the Ex=-Eg diagonal. (but do we need to do that?)

**Comment by fzeiser** [comment]
@cecgresonant @vetlewi: Any opinions on this here?

**Comment by cecgresonant** [comment]
I am not sure that I understood all your points, but here are some first thoughts:
1. I do not see a problem with getting a level density below Ex = 0 MeV, as long as the resulting NLD is in accordance with the resolution. 

2. I agree with you that the average gSF is going to be affected by the low-statistics "tails" from direct-decay "diagonals". However, I am not sure if this is a big effect as long as there is plenty of bins with good statistics above. My guess is that this is most important at the upper bin included in "rhosigchi" (defined by Ex_max), and that it would give a gSF that drops off at the highest Eg. 

I am more worried about our treatment of the "in-between diagonals" regions. For example, in the tin isotopes, there is a ~1-MeV gap between the decay to the ground state and to the 1st Ex. This means there are a lot of bins with zero counts in them. As of now, I think this "gap" is included in the extraction of the gSF, although it should not be because there is no information here that should be used in the gSF extraction! How can we handle this in a better way?

**Comment by fzeiser** [comment]
> I do not see a problem with getting a level density below Ex = 0 MeV, as long as the resulting NLD is in accordance with the resolution.
 1. I simply think that it's confusing to see a graph where you have a NLD  with `Ex<0`. I agree that one may argue for something like the resolution - but i) it's still confusing on first sight (for any non-Oslo method familiar person), and b) the second point on the erroneous results for very high `Eg` in the `gsf` will carry through to the `nld` at very low `Ex`

 2. Yes, that is exactly my point, may impact the very last points in the gsf and very first ("negative Ex") points of the nld. I have often seen a strange behavior of these last bins, with almost arbitrary drops/spikes depending on how I choose the extraction region. I think this here might be the reason for it.

> I am more worried about our treatment of the "in-between diagonals" regions

My ideas: 
- Use another test statistics (not weighted chi^2) #28; which I think is invalid for very low number of counts, certainly for `N=0` as `sigma=0` gives problems in `weights = 1 / sigma`. It might be challenging as we currently probably don't get "clean", i.e. zero-counts regions in between such levels
- Fix the level density at low Ex: Provided a level scheme from discrete levels and the detector resolution, we can fix the first `n` bins of the `nld`. If one has information about spin-dependent population cross-section, one might use this to exclude some levels, as we may not populate them in out experiment. 
- Even if you don't fix the nld; one might use an initial condition that reflects our thoughts: reduce nld in this region...

**Comment by cecgresonant** [comment]
> > I do not see a problem with getting a level density below Ex = 0 MeV, as long as the resulting NLD is in accordance with the resolution.
> 
> 1. I simply think that it's confusing to see a graph where you have a NLD  with `Ex<0`. I agree that one may argue for something like the resolution - but i) it's still confusing on first sight (for any non-Oslo method familiar person), and b) the second point on the erroneous results for very high `Eg` in the `gsf` will carry through to the `nld` at very low `Ex`

Well, any experimentalist would be familiar with the issue of detector resolution in general. This is not something "we may argue" - it is an experimental fact. That said, it would not hurt to be explicit about this in the papers (a comment in the NLD figure caption, for example). Also, the NLD data points should drop off when Ex < 0 MeV, which again indicates that this is due to experimental resolution. But here it seems to be a problem with OMpy that I don't understand, which might deserve a devoted issue. I attach a screen shot of Francesco's result of the NLD for 117Sn, which seems to shoot up again at Ex < 0 MeV, after first showing the usual (and expected) drop-off. But at Ex ~-500 keV the NLD increases by a factor of 10. I wonder why?
![Screenshot 2019-11-18 at 14 45 54](https://user-images.githubusercontent.com/15776247/69058158-6f870f00-0a13-11ea-92f1-ab3f507bfeb2.png)

> 2. Yes, that is exactly my point, may impact the very last points in the gsf and very first ("negative Ex") points of the nld. I have often seen a strange behavior of these last bins, with almost arbitrary drops/spikes depending on how I choose the extraction region. I think this here might be the reason for it.
> 
> > I am more worried about our treatment of the "in-between diagonals" regions
> 
> My ideas:
> 
> * Use another test statistics (not weighted chi^2) #28; which I think is invalid for very low number of counts, certainly for `N=0` as `sigma=0` gives problems in `weights = 1 / sigma`. It might be challenging as we currently probably don't get "clean", i.e. zero-counts regions in between such levels
I like this idea, we could maybe let the user define regions that should not be included in the fit?

> * Fix the level density at low Ex: Provided a level scheme from discrete levels and the detector resolution, we can fix the first `n` bins of the `nld`. If one has information about spin-dependent population cross-section, one might use this to exclude some levels, as we may not populate them in out experiment.
Probably, but I am a bit hesitant as the best would be for the NLD to just come out of the data we have. But yes, especially for cases with a restricted, populated spin range this could be useful to consider.
> * Even if you don't fix the nld; one might use an initial condition that reflects our thoughts: reduce nld in this region...
Yes something we could consider...

**Comment by fzeiser** [comment]
> But here it seems to be a problem with OMpy that I don't understand, which might deserve a devoted issue. I attach a screen shot of Francesco's result of the NLD for 117Sn, which seems to shoot up again at Ex < 0 MeV,

This has been fixed in 4f84776d4143fc3cded8bd6447de0eda07e7b03e:

> - set values of the nld and gsf that are not constrained by the
>   minimization routine to np.nan. This can happen, as we create equal
>   binned nld/gsf for all matrices, but some may not have counts in the
>   last bins close to the diagonal. We can choose either to cut the nld
>   and gsf vectors directly, but then receiving differently sized vectors,
>   or, as chosen here, set the unconstrained elements to np.nan.

**Comment by fzeiser** [comment]
> Well, any experimentalist would be familiar with the issue of detector resolution in general. This is not something "we may argue" - it is an experimental fact

It's not the detector resolution that I think we have to argue for/against. But if we choose to use a fine binning, where we publish results for negative Ex, I think this is something one has to write about  (+ as mentioned may have some effect of the results).

Let's compare it to following situation: When we receive negative counts in the unfolded / fg matrix, we delete them, arguing that this is not physical. For me, the same should yield for the nld. An easy way to avoid this situation would be to rebin with the fwhm as proposed above. Another argument that bases on a discussion I've had with Darren would be why we use 1 sigma of `Ex = Eg + dE`, and how this would change for 2 sigma, 3 sigma, .... The problems I've stated are true for 1 sigma, but they get more extreme for eg.  `Ex = Eg + 5 sigma`.

**Comment by cecgresonant** [comment]
This makes little sense to me, probably I need to get over the cold before looking into it :) Okay, so I disagree, here are some of my arguments: 
(a) The resolution is, at least to me, a completely different thing than removing negative counts. A better analogy would perhaps be our prompt time peak, that has also counts on the left flank ("negative" times). I do not think it is not a good idea to make the binning so coarse that only one bin would describe, e.g., the ground state. Then we would deliberately ignore the information that is given by the resolution! I would at least like to see the data be wrapped around the ground state, the first excited state and so on, if we can, and that requires at least enough bins to describe a peak (~3 bins). 

(b) I have no idea what you have discussed with Darren, but given that we stay within the frequentist approach, the normal way of presenting uncertainties is to give a 1-sigma uncertainty.   If we are to change that, we would have to have a strong motivation why. That said - I thought it is indeed the FWHM that is used in rhosigchi, and not 1-sigma for the resolution?

**Comment by fzeiser** [comment]
It's fair enough to disagree  :smile: . But I disagree/want to clarify this one he
on (b)
> but given that we stay within the frequentist approach, the normal way of presenting uncertainties is to give a 1-sigma uncertainty.

To present the errors as as 1 sigma is a convention in our field only, potentially in physics in more general. 1 sigma doesn't have anything with the frequentist approach to do; one could have  freely chosen 2 sigma, 3 sigma or any other value instead. In fact, see wikipedia:

> The confidence level is designated prior to examining the data. Most commonly, the 95% confidence level is used.[4] However, other confidence levels can be used, for example, 90% and 99%. 

on (a):
If we were to accept a finer binning, we should still make sure to correct for the gsf variations in the highest energy bins.

**Comment by cecgresonant** [comment]
> It's fair enough to disagree 😄 . 
A good discussion is always useful 😄

> But I disagree/want to clarify this one he
> on (b)
> 
> > but given that we stay within the frequentist approach, the normal way of presenting uncertainties is to give a 1-sigma uncertainty.
> 
> To present the errors as as 1 sigma is a convention in our field only, potentially in physics in more general. 1 sigma doesn't have anything with the frequentist approach to do; one could have freely chosen 2 sigma, 3 sigma or any other value instead. In fact, see wikipedia:
> 
> > The confidence level is designated prior to examining the data. Most commonly, the 95% confidence level is used.[4] However, other confidence levels can be used, for example, 90% and 99%.
> 
I should perhaps have specified that I am thinking of our field, but my feeling is that this is quite usual in other fields as well. For our field, if you look up levels in NuDat or resonance spacings in RIPL or Mughabghab, for example, the quoted uncertainties are 1 sigma. If the uncertainty is given as 2 sigma or more, it is explicitly said.

> on (a):
> If we were to accept a finer binning, we should still make sure to correct for the gsf variations in the highest energy bins.

I agree. This is something we should think through.

**Comment by fzeiser** [comment]
We concluded that we recommend choosing the 1/2 FWHM of the detector resolution as the bin-width; of course any user can decide on using another bin-width if wanted.
